### ISSUE TITLE
ASPSP Simulator - move OB data model module and 3rd party dependencies into common projects

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#15]
## Story

As a member of the ForgeRock Open Banking Team
I want to have all the third party dependencies and shared FR dependencies in one place
so that the dependencies are easy to manage and update between releases

## Acceptance criteria

- All third party dependencies are in `securebanking-parent`
- `securebanking-openbanking-aspsp-model` has been replaced by `securebanking-common-openbanking-uk-datamodel`
- `securebanking-openbanking-aspsp` consumes the `secure-banking-parent` and `securebanking-common-openbanking-uk-datamodel`

## Tasks

- [x] Copy latest changes from `securebanking-openbanking-aspsp-model` to `securebanking-common-openbanking-uk-datamodel`
- [x] Remove `securebanking-openbanking-aspsp-model` (but keep multi-module structure with single module for now?).
- [x] Move third party libraries from `securebanking-openbanking-aspsp` to `securebanking-parent` and extend this parent pom instead of `spring-boot-starter-parent`.

### Release Notes

Affected App: `securebanking-openbanking-aspsp`

**Comment by matt-wills** [comment]
Duplicate of #27
