### ISSUE TITLE
Use GitHub Actions to build maven based Java projects

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#17]
## Story

As a member of ForgeRock's Open Banking Team
I want a build to take place each time I make a change to one of the maven based projects
So that I have confidence I have not broken anything and the project can be deployed

## Acceptance criteria
A build takes place whenever:
- A PR is raised
- A PR is merged to master
- A release is created (including the artifact being pushed to ForgeRock's artifactory)

## Repositories that need action workflows added
- [ ] [securebanking-openbanking-aspsp](https://github.com/SecureBankingAcceleratorToolkit/securebanking-openbanking-aspsp)

Some existing GitHub workflows we can consider using:
https://github.com/SecureBankingAcceleratorToolkit/securebanking-parent/tree/master/.github/workflows

or

https://github.com/SecureBankingAcceleratorToolkit/securebanking-parent/tree/master/.github/workflows

## Tasks

- [ ] Workflow for when a PR is raised
- [ ] Workflow for when a PR is merged
- [ ] Workflow for when a release is created

### Release Notes

Affected App: All existing secure-banking Maven based Java projects
