### ISSUE TITLE
Create an initial mock bank (ASPSP) SpringBoot project for Open Banking

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#2]
## Story

As a TPP 
I want to be able to test my application against a bank simulator
so that I can be assured my application will work against a real ASPSP

## Acceptance criteria
- The mock bank supports v3.0 onwards of the Open Banking Read/Write REST API.
- The mock bank does not authenticate or authorise the client - any client with appropriate network access can send/receive HTTP requests/responses.
- Open Banking API objects are converted to FR domain objects and stored in mongo.

## Tasks
List of tasks required to implement this story

- [x] Create initial SpringBoot maven based project with the groupId `com.forgerock.sba.aspsp` and artifactId `forgerock-sba-mock-aspsp`.
- [x] Port "common" code (e.g. repositories, mongo document classes, FR domain model and converters) from `openbanking-aspsp`.
- [x] Copy the required snippets of code from `openbanking-openbanking-model`, thereby allowing a self contained project.
- [x] Refactor the package structure, making the separation of layers more obvious.
- [x] Use embedded MongoDB for SpringBoot tests, rather than docker-compose.
- [x] Generate the OB model objects within this project (e.g. as a sub-module).
- [x] Add a simple example controller for the payments API (to prove the project works end-to-end using postman).

### Release Notes

Affected App: `forgerock-sba-mock-aspsp`

**Comment by matt-wills** [comment]
All tasks complete.
