### ISSUE TITLE
Improve securebanking-openbanking-demo with a local environment profile (IG development mode)

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#20]
## Story

As a developer/customer I want to deploy the IG component in `DEVELOPMENT` mode so that I can access the ui and `IG Studio` to help build and deploy the IG configuration in the local environments.

## Acceptance criteria

- IG deployed in `DEVELOPMENT` mode.
- Can access the `IG UI` and `IG Studio`.
- The existing routes configured can see in the UI in `deployed` status.

## Tasks
- [x] Create a `IG local` configuration for `obdemo-bank`
- [x] Prepare the `IG local` configuration to deploy it in `DEVELOPMENT` mode (UI and Studio)
- [x] Create a docker stage for `IG local`
- [x] Create a profile to deploy local environments with `IG local` 
- [x] Upgrade `config.sh` script to init `IG local`
- [x] Create the kustomize configuration for `IG local`
- [x] Upgrade skaffold descriptor with a new profile to deploy `obdemo-bank` with `IG local` for local environments
- [x] Update the readme files to introduce the new changes

### Release Notes

Affected App: `securebanking-openbanking-demo`

Description: X
<end release notes>

**Comment by jorgesanchezperez** [comment]
![Screenshot 2020-12-09 at 17 26 44](https://user-images.githubusercontent.com/54277573/101664505-d541a100-3a43-11eb-9e89-4faf9168cb7a.png)
