### ISSUE TITLE
Create functional test project in the SecureBankingAcceleratorToolkit

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#29]
## Story

As a developer I want to run functional tests so that I can determine correct system behaviour.

## tasks
- [x] Create repository and initial commit
- [x] Add test filters using `@Tag` junit annotation
- [x] Create the test tasks filtering by `@Tag` junit annotation

## Acceptance criteria

- we have sb-functional-tests

**Comment by jorgesanchezperez** [comment]
- Repository: [securebanking-openbanking-uk-functional-tests](https://github.com/SecureBankingAcceleratorToolkit/securebanking-openbanking-uk-functional-tests)

### Tasks

| Code Generation | Description |
| --- | --- |
| gen-pain00100108-source | Generate sources for the schema schema-pain.001.001.08 |
| xjcGeneration | Run all XJC tasks |

| Forgerock | Description |
| --- | --- |
| generateTestJar | Generate a non-executable jar library tests |

| Forgerock-tests | Description |
| --- | --- |
| accessToken | Runs the access token tests |
| account | Runs the account tests |
| bank | Runs the bank tests |
| directory | Runs the directory tests |
| dynamicRegistration | Runs the dynamic registration tests |
| event | Runs the event tests |
| matls | Runs the matls tests |
| payment | Runs the payment tests |
| serviceHealthCheck | Runs the test to check the service status |
| test | Runs ALL tests |
