### ISSUE TITLE
Creation of multipurpose securebanking-openig-jws-signing helper library to use in IG

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#3]
## Story

As a ASPSP I want to be able to generate and verify the Open Banking `detached-jws-signature` header extending the IG (HTTP Gateway) so that the application fulfils the security requirements of the Open Banking Read/Write API

## Acceptance criteria
- The ASPSP to be able to signing the message and generate the `detached-jws-signature` header
- The ASPSP to be able verify the `detached-jws-signature` header

## Tasks
List of tasks required to implement this story

- [ ] Create initial repository java library with groupId `com.forgerock.securebanking.jws` and artifactId `securebanking-jws-signature`
- [ ] Translate and merge source from `jwkms` and `aspsp` detached filters and generators to `securebanking-jws-signature`
- [ ] Create the proper unit tests
- [ ] Embedding the Customization in IG

### To evaluate
- [ ] Extending IG through java API (Filter) creating a IG java library extension or embedded on the artifact `securebanking-jws-signature` created.

### Release Notes

Affected App: `IG 7.0`

**Comment by jorgesanchezperez** [comment]
Closing and replaced by the issue https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/7
