### ISSUE TITLE
Provide supported Read/Write API URLs via Discovery endpoint

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#5]
## Story

As a TPP
I want to be able to retrieve all the supported Read/Write API URLs
so that I can see which versions are supported and which URL I need to use

## Acceptance criteria

- An ASPSP Discovery endpoint returns all the supported URLs for the Read/Write API
- All versions from 3.0 onwards can be provided
- The list of supported URLs is configurable

## Tasks

- [x]  Support the discovery API endpoint (a precursor for the ResourceLinkService).
- [x]  Block endpoints that have been explicitly disabled in the config.
- [x] Document how to enable/disable endpoints in the config.
- [x] Generate the swagger spec for the Discovery endpoint.

### Release Notes

Affected App: securebanking-openbanking-aspsp-mock
