### ISSUE TITLE
Secure banking User interfaces [EPIC DRAFT]

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#69]
## Story
As a `customer/platform consumer` I want to have the `User Interfaces` so can manage  the resources access such as accept or reject the consents.

# tasks
- [ ] [44: Ui base project](https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/44)

**Nx tool to manage a mono repo and use schematics power**
- [ ] Upgraded angular version on UI apps `ng update` 8 to 11.
- [ ] Re-Organise the libraries, modules and share components
- [ ] Upgrade architecture secure banking UI applications to `multi project` mono repository
## Acceptance criteria
- [ ] Have minimal UI's repository
- [ ] Have minimal UI's applications working
- [ ] Have minimal UI's applications working against cloud platform
