### ISSUE TITLE
IG scripting - Open Banking `detached-jws-signature` header extending the IG (HTTP Gateway)

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#7]
## Story

As a ASPSP I want to be able to generate and verify the Open Banking `detached-jws-signature` header thru IG (HTTP Gateway) so that the application fulfils the security requirements of the Open Banking Read/Write API

## Acceptance criteria
- The ASPSP to be able to signing the message/jwt and generate the `detached-jws-signature` header
- The ASPSP to be able verify the `detached-jws-signature` header

## Tasks
List of tasks required to implement this story

- [ ] Create temporal repository to save the scripts, they will move later to the proper repository (obdemo-forgeops pending to move into github or similar).
- [ ] Create the scripts to verify and signing the `detached-jws-signature`.
- [ ] Create the routes chain/filters and generators to `securebanking-jws-signature` for IG.
- [ ] Create the IG `securebanking-jws-signature` configuration.
- [ ] Apply the routing in IG, deploy the routes `securebanking-jws-signature` configuration to IG.
- [ ] Create proper tests in postman or another test tool.

### Release Notes

Affected App: `IG 7.0`

**Comment by christian-brindley** [comment]
The proposal is to use out of the box IG filters to handle inbound and outbound signatures.

For outbound signatures, we can use the IG JwtBuilderFilter to create a detached signature. The only drawback is that JwtBuilderFilter does not include a kid in the JWT header. This has been addressed by OPENIG-5053 which will be included in IG 7.1.0.

For inbound signatures, we should be able to use the IG JwtValidationFilter to verify the signature against the TPP public key. However, JwtValidationFilter requires the verification key to be in a secret store which is defined in static configuration. This is an issue for OB, because the validation keys need to be fetched from a JWKS URL only known at runtime (i.e. we look up the JWKS URL for a TPP at request time).

Possible solutions to this inbound issue are:

- Wait for a fix to IG to support runtime JWKS URIs - bugster OPENIG-5236
- Use a scripted client handler with the JwkSetSecretStore to redirect to a specific JWKS URL at runtime. The issue with this is that the JWKS is cached, and reloading through scripting hangs the route.
- Use a FileSystemSecretStore and fetch keys through a script at runtime. This issue with this is that the FileSystemSecretStore appears to be loaded at startup, with new files not recognised.
- Create an IDM custom endpoint that acts as a composite JWKS URI for all TPPs. Issue with this is that there is a minimum cache time in IG, so a newly registered TPP will not pick up the JWKS until the cache is refreshed (this may be acceptable). Also, custom endpoints are awkward in FIDC because there is not interface for them, and debugging is difficult.
- Custom library/script to handle JWT validation without the IG JwtValidationFilter. Issue with this is that we now have additional code to maintain, which will not be supported by product/support teams.

**Comment by christian-brindley** [comment]
Settled on IDM custom endpoint approach. The endpoint 
- Pulls the JWKS URIs for all registered TPP
- Makes an HTTP request to each URI to retrieve keys
- Builds a new JWK set consisting of all signing keys from all TPPs 
- Returns this JWK set to the caller

IG is configured with this endpoint as the URI for the `JwkSetSecretStore` used for the JwtValidationFilter. 

Pros
- Simple out of the box config for IG
- No scripting required in IG

Cons
- Dependency on IDM
- Potentially very large JWK set
- IG caches JWK set, so any newly registered TPP won't be able to submit payment request until next cache refresh (default 2 minutes max)
