### ISSUE TITLE
Dockerize the ASPSP simulator SpringBoot project

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#8]
## Story

As a customer of the Secure Banking Accelerator Toolkit
I want the ASPSP simulator to run in Docker (including `docker-compose`)
So that I can reliably and easily deploy the ASPSP simulator in any environment.

## Acceptance criteria
- A runnable docker image of the application is pushed to a docker repository whenever a maven deploy is performed.
- The application and its dependencies can be started using `docker-compose`.

## Tasks
- [ ] Determine which maven docker plugin to use (e.g. `jib-maven-plugin` or `dockerfile-maven-plugin`?)
- [ ] Add the required configuration to the project's pom files (parent and child).
- [ ] Test the application runs using both `docker run` and `docker-compose`.

### Release Notes
Affected App: `securebanking-openbanking-aspsp-simulator`

**Comment by matt-wills** [comment]
Suggested version of docker-compose plugin:
```<docker-compose-maven-plugin.version>2.5.1</docker-compose-maven-plugin.version>```

And if we go with the dockerfile-maven-plugin:
```<dockerfile-maven-plugin.version>1.4.13</dockerfile-maven-plugin.version>```

**Comment by matt-wills** [comment]
Implemented by these two PRs:

- https://github.com/SecureBankingAcceleratorToolkit/securebanking-openbanking-aspsp/pull/11
- https://github.com/SecureBankingAcceleratorToolkit/securebanking-openbanking-aspsp/pull/14

There are a few additional things to consider:

- It might be necessary to create a service account for the main docker registry (I experienced authentication failures when pulling certain JRE images, but this seems to have stopped and I haven't investigated it further!).
- We could create a separate maven profile for pushing the docker image to the gcr registry, or just rely on releases (release:perform will run the maven deploy phase, which will push the image). Alternatively, just running `mvn compile jib:build` will do this.
- According to the documentation, Jib integrates with Skaffold, which may be something to look into: https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#skaffold-integration
