### ISSUE TITLE
Extend and implement custom features - Customer

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#9]
## Story

As a customer of the Secure Banking Accelerator Toolkit
I want a methodology/pattern/rules to extend the Secure Banking Functionalities or implement custom features.
So that I can reliably and easily deploy my custom features

## Acceptance criteria
- A defined methodology/pattern/rules to extend the Secure Banking Functionalities or implement custom features.
- Easily deployment of extension and custom features.
- Avoid implement extensions or custom features on the source core to make reliably the upgrades and updates on the core to minimise the disruptions for existing extensions and custom features.

## Tasks
* [x] Investigate different ways to extend and implement custom features on secure banking accelerator toolkit.
* [x] Prepare a Spring boot application PoC that represent a base for an extension and custom features solution that complies the acceptance criteria.
* [ ] Define a methodology/pattern/rules to extend or implement a custom features.

### Release Notes
Affected App: secure banking extensions and custom features.

**Comment by jorgesanchezperez** [comment]
Proof of Concept Source:
- [securebanking-extensions-poc](https://stash.forgerock.org/users/jorge.sanchez-perez/repos/securebanking-extensions-poc/browse)
